name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Install GUI
        run: | 
          sudo apt-get install xorg
          sudo apt-get install --no-install-recommends openbox
          sudo apt-get install gnome-calculator
          
      - name: Try xinit
        run: |
          echo "/usr/bin/openbox-session" >> ~/.xsession
          sudo startx
#          exec openbox-session
#          su -c 'startx gnome-calculator -- :1' runner
#          sudo startx gnome-calculator -- :1
#          sudo xinit /usr/ucb/rsh fasthost cpupig -display ws:1 --  :1 -a 2 -t 5
