name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Install GUI
        run: | 
          sudo apt install xorg
          sudo apt install --no-install-recommends openbox
          
      - name: Try xinit
        run: |
          xinit /usr/ucb/rsh fasthost cpupig -display ws:1 --  :1 -a 2 -t 5
